import type { Metadata } from "next";
import { BuildingIcon, CheckIcon, ShieldIcon, SparklesIcon } from "@/components/icons";

export const metadata: Metadata = { title: "For agencies & sellers" };

export default function ListPropertyPage() {
  return <div className="page-top page-shell seller-page">
    <section className="seller-hero"><div><div className="eyebrow">For agencies & verified sellers</div><h1>Fewer calls.<br/><span>Better-qualified buyers.</span></h1><p>List transaction-ready homes and let Finqit handle fair reservation access, viewing windows and buyer readiness before your team gets buried in calls.</p><div className="hero-actions-row"><button className="button button-primary">Start listing</button><button className="button button-secondary">Talk to us</button></div></div><div className="seller-hero-panel"><div className="seller-panel-top"><span className="dashboard-icon blue"><BuildingIcon/></span><span className="pill pill-green">Listing ready</span></div><h3>Carrer de Prat de la Riba · Sabadell</h3><div className="seller-status-list"><span><CheckIcon/> Ownership / mandate verified</span><span><CheckIcon/> Required listing data complete</span><span><CheckIcon/> Reservation terms accepted</span><span><CheckIcon/> Instant Reserve enabled</span></div><div className="seller-reservation"><div><small>Next eligible buyer</small><strong>Identity verified · funds method ready</strong></div><span>Queue #1</span></div></div></section>
    <section className="section seller-benefits"><div className="section-heading centered-heading"><div className="eyebrow">Why Finqit</div><h2>Turn demand into an orderly process.</h2></div><div className="benefit-grid"><article><ShieldIcon/><h3>Verified before exposure</h3><p>Collect the mandate and key property data before Instant Reserve is activated.</p></article><article><SparklesIcon/><h3>Qualified matching</h3><p>Buyer agents surface people whose hard requirements actually fit the property.</p></article><article><BuildingIcon/><h3>One reservation at a time</h3><p>Reduce no-shows and overlapping visits while keeping access transparent.</p></article></div></section>
    <section className="agency-steps"><div><div className="eyebrow">Agency workflow</div><h2>Built around the way a real transaction happens.</h2></div><ol><li><span>01</span><div><strong>Verify seller mandate</strong><p>Owner identity, authority to market, registry reference and key documents.</p></div></li><li><span>02</span><div><strong>Publish transaction-ready listing</strong><p>Price, facts, disclosures, viewing rules and standardised reservation conditions.</p></div></li><li><span>03</span><div><strong>Let Finqit allocate fairly</strong><p>Eligible buyers are ordered by published rules, not by who knows the agent.</p></div></li><li><span>04</span><div><strong>Meet the buyer once it matters</strong><p>Manage the visit and continue the sale with a buyer who already committed to the process.</p></div></li></ol></section>
  </div>;
}
